In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
df = pd.read_csv('/Users/sky/class_python/6.Recommendation/jobkorea_saramin_recruit.csv', index_col=0)
# 인덱스 중복되는게 나와서 초기화하고 시작. ㅇㅅㅇ
df.reset_index(inplace=True)
df.head(3)

index  resource     company                           duty career degree  \
0      0  jobkorea  디휴브(DEHUV)                 [디휴브] 개발자 부문채용  신입·경력   학력무관   
1      1  jobkorea    ㈜레미유코스메틱  브랜드 디자이너 / MD / (카페)쇼룸 매니저 채용     경력   학력무관   
2      2  jobkorea         ㈜순진       마케팅 담당자 및 상품기획/MD 경력직 채용  경력2년↑    고졸↑   

  work_place                work_type  \
0     경기 고양시                      정규직   
1     서울 성동구  정규직                 외\n   
2     서울 광진구                      정규직   

                                            category  \
0  ['반응형 웹, 백엔드, 풀스택, 하이브리드 앱, 소프트웨어개발, BigData, ...   
1  ['화장품, 마케팅, 마케팅기획, 브랜딩, 프로모션, 상품기획, 신상품개발, 온라인...   
2  ['영상편집, 포토샵, 제품기획, 광고기획, 마케팅, 마케팅기획, 바이럴마케팅, 브...   

                                                link  \
0  https://www.jobkorea.co.kr/Recruit/GI_Read/366...   
1  https://www.jobkorea.co.kr/Recruit/GI_Read/366...   
2  https://www.jobkorea.co.kr/Recruit/GI_Read/366...   

                                                info  
0  https://www.jobkorea.co.kr/Recruit/Co_Read/C/d...  
1  https://www.jobkorea.co.kr/Recruit/Co_Read/C/l...  
2  https://www.jobkorea.co.kr/Recruit/Co_Read/C/s...

In [5]:
company = df['company'].tolist()

In [6]:
category = df['category']
category = category.to_list()
type(category)

list

In [7]:
#Counter Vectorizer 형태로 변형하깅
count =  CountVectorizer(max_features=100)
a = count.fit_transform(category)
a

<47645x100 sparse matrix of type '<class 'numpy.int64'>'
	with 207481 stored elements in Compressed Sparse Row format>

47645개 문장에 6444 단어가 이씀. -> 100개만 써보기로.

In [6]:
a.toarray()

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
# value 기준으로 정렬
sorted(count.vocabulary_, reverse=True)

['하드웨어',
 '프리미어',
 '프론트엔드',
 '프로모션',
 '포토샵',
 '펌웨어',
 '퍼블리셔',
 '키워드광고',
 '컨텐츠기획',
 '컨텐츠관리',
 '컨텐츠개발',
 '카페',
 '정보통신',
 '정보보안',
 '전자상거래',
 '자바스크립트',
 '임베디드',
 '일러스트레이터',
 '인공지능',
 '응용프로그래머',
 '유지보수',
 '웹프로그래머',
 '웹표준',
 '웹퍼블리셔',
 '웹접근성',
 '웹서비스기획',
 '웹사이트운영',
 '웹마케팅',
 '웹기획',
 '웹광고기획',
 '웹개발',
 '웹ui',
 '온라인마케팅',
 '온라인md',
 '오픈마켓',
 '영상편집',
 '앱개발',
 '안드로이드',
 '아이폰',
 '시스템운영',
 '시스템엔지니어',
 '시각디자인',
 '쇼핑몰',
 '솔루션',
 '소프트웨어개발',
 '소프트웨어',
 '소셜커머스',
 '소셜미디어',
 '소셜마케팅',
 '서버관리자',
 '서버개발',
 '상품기획',
 '빅데이터',
 '블로그관리',
 '백엔드',
 '바이럴마케팅',
 '모바일앱개발',
 '모바일기획',
 '모바일ui',
 '머신러닝',
 '마케팅기획',
 '마케팅',
 '네트워크엔지니어',
 '네트워크관리',
 '네트워크',
 '기술지원',
 '광고디자인',
 '광고기획',
 '게임개발',
 '게시판관리',
 'windows',
 'ux디자인',
 'ux',
 'ui',
 'sql',
 'sm',
 'si',
 'se',
 'qa',
 'python',
 'pm',
 'php',
 'oracle',
 'net',
 'mysql',
 'ms',
 'md',
 'linux',
 'jsp',
 'java',
 'it컨설팅',
 'html5',
 'html',
 'erp',
 'dba',
 'css',
 'asp',
 'api',
 'android',
 'ai']

In [8]:
# matrix에 인덱스와 컬럼 값 넣기
import pandas as pd
count_df = pd.DataFrame(a.toarray(), columns= sorted(count.vocabulary_))
count_df.index = company
count_df

ai  android  api  asp  css  dba  erp  html  html5  it컨설팅  ...  \
디휴브(DEHUV)      1        0    1    0    0    1    0     0      0      0  ...   
㈜레미유코스메틱        0        0    0    0    0    0    0     1      1      0  ...   
㈜순진             0        0    0    0    0    0    0     0      0      0  ...   
효성에프엠에스㈜        0        0    1    3    0    0    0     1      1      0  ...   
㈜빗썸코리아          0        0    0    0    0    1    0     0      0      0  ...   
...            ..      ...  ...  ...  ...  ...  ...   ...    ...    ...  ...   
케이아이디비자금중개(주)   0        0    0    0    0    0    0     0      0      0  ...   
(주)파폼           0        0    0    0    0    0    0     0      0      0  ...   
(주)엔엠에스컨설팅      0        0    0    0    0    0    0     0      0      0  ...   
(주)여의도사람들       0        0    0    0    0    0    0     0      0      0  ...   
인천웨딩 주식회사       0        0    0    0    0    0    0     0      0      0  ...   

               컨텐츠관리  컨텐츠기획  키워드광고  퍼블리셔  펌웨어  포토샵  프로모션  프론트엔드  프리미어  하드웨어  
디휴브(DEHUV)         0      0      0     0    0    0     0      0     0     0  
㈜레미유코스메틱           0      0      0     0    0    2     1      0     0     0  
㈜순진                1      0      0     0    0    1     0      0     0     0  
효성에프엠에스㈜           0      1      0     0    1    0     0      0     0     0  
㈜빗썸코리아             0      1      1     0    1    1     2      0     0     0  
...              ...    ...    ...   ...  ...  ...   ...    ...   ...   ...  
케이아이디비자금중개(주)      0      0      0     0    0    0     0      0     0     0  
(주)파폼              0      0      0     0    0    0     0      0     0     0  
(주)엔엠에스컨설팅         0      0      0     0    0    0     0      1     0     0  
(주)여의도사람들          0      0      0     0    0    0     0      1     0     0  
인천웨딩 주식회사          0      0      0     0    0    0     0      0     0     0  

[47645 rows x 100 columns]

# 유사도 계산

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
sim_table = cosine_similarity(count_df, count_df)

In [10]:
#sim_table.shape
np.argsort(sim_table[0]) #기본 오름차순 정렬

array([23822, 25835, 25833, ...,  1050, 17990,     0])

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

#유클리디언, 맨해튼은 정규화가 필요함
def normalize(v):
    norm = np.sum(v)
    return v / norm

norm_df = normalize(count_df)

print(euclidean_distances(norm_df[0:1], norm_df[1:2]))

[[0.00451572]]


In [12]:
from sklearn.metrics.pairwise import manhattan_distances
print(manhattan_distances(norm_df[0:1], norm_df[1:2]))

[[0.02472909]]


# TF-IDF

In [8]:
tfidf =  TfidfVectorizer(max_features=100)
b = tfidf.fit_transform(category)
b

<47645x100 sparse matrix of type '<class 'numpy.float64'>'
	with 207481 stored elements in Compressed Sparse Row format>

In [9]:
tfidf_df = pd.DataFrame(b.toarray(), columns=sorted(tfidf.vocabulary_))
tfidf_df.index = company
tfidf_df

ai  android       api       asp  css       dba  erp  \
디휴브(DEHUV)     0.143224      0.0  0.135119  0.000000  0.0  0.139138  0.0   
㈜레미유코스메틱       0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
㈜순진            0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
효성에프엠에스㈜       0.000000      0.0  0.107045  0.348477  0.0  0.000000  0.0   
㈜빗썸코리아         0.000000      0.0  0.000000  0.000000  0.0  0.151016  0.0   
...                 ...      ...       ...       ...  ...       ...  ...   
케이아이디비자금중개(주)  0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
(주)파폼          0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
(주)엔엠에스컨설팅     0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
(주)여의도사람들      0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   
인천웨딩 주식회사      0.000000      0.0  0.000000  0.000000  0.0  0.000000  0.0   

                   html     html5  it컨설팅  ...     컨텐츠관리     컨텐츠기획     키워드광고  \
디휴브(DEHUV)     0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   
㈜레미유코스메틱       0.150208  0.212090    0.0  ...  0.000000  0.000000  0.000000   
㈜순진            0.000000  0.000000    0.0  ...  0.213403  0.000000  0.000000   
효성에프엠에스㈜       0.081393  0.114926    0.0  ...  0.000000  0.117838  0.000000   
㈜빗썸코리아         0.000000  0.000000    0.0  ...  0.000000  0.161441  0.149812   
...                 ...       ...    ...  ...       ...       ...       ...   
케이아이디비자금중개(주)  0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   
(주)파폼          0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   
(주)엔엠에스컨설팅     0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   
(주)여의도사람들      0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   
인천웨딩 주식회사      0.000000  0.000000    0.0  ...  0.000000  0.000000  0.000000   

               퍼블리셔       펌웨어       포토샵      프로모션     프론트엔드  프리미어  하드웨어  
디휴브(DEHUV)      0.0  0.000000  0.000000  0.000000  0.000000   0.0   0.0  
㈜레미유코스메틱        0.0  0.000000  0.292077  0.225554  0.000000   0.0   0.0  
㈜순진             0.0  0.000000  0.168624  0.000000  0.000000   0.0   0.0  
효성에프엠에스㈜        0.0  0.113296  0.000000  0.000000  0.000000   0.0   0.0  
㈜빗썸코리아          0.0  0.155219  0.108416  0.334892  0.000000   0.0   0.0  
...             ...       ...       ...       ...       ...   ...   ...  
케이아이디비자금중개(주)   0.0  0.000000  0.000000  0.000000  0.000000   0.0   0.0  
(주)파폼           0.0  0.000000  0.000000  0.000000  0.000000   0.0   0.0  
(주)엔엠에스컨설팅      0.0  0.000000  0.000000  0.000000  0.460116   0.0   0.0  
(주)여의도사람들       0.0  0.000000  0.000000  0.000000  0.409397   0.0   0.0  
인천웨딩 주식회사       0.0  0.000000  0.000000  0.000000  0.000000   0.0   0.0  

[47645 rows x 100 columns]

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
sim_table2 = cosine_similarity(tfidf_df, tfidf_df)
np.argsort(sim_table2[0])

array([23822, 25835, 25833, ..., 20231, 17990,     0])

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

def normalize(v):
    norm = np.sum(v)
    return v / norm

norm_b = normalize(tfidf_df)

print(euclidean_distances(norm_b[0:1], norm_b[1:2]))

[[0.00209929]]


In [12]:
from sklearn.metrics.pairwise import manhattan_distances

def normalize(v):
    norm = np.sum(v)
    return v / norm

norm_b = normalize(tfidf_df)

print(manhattan_distances(norm_b[0:1], norm_b[1:2]))

[[0.01102229]]


In [13]:
np.round(sim_table2, 4)

array([[1.    , 0.    , 0.    , ..., 0.0438, 0.039 , 0.    ],
       [0.    , 1.    , 0.3698, ..., 0.    , 0.    , 0.1367],
       [0.    , 0.3698, 1.    , ..., 0.    , 0.    , 0.4506],
       ...,
       [0.0438, 0.    , 0.    , ..., 1.    , 0.6433, 0.    ],
       [0.039 , 0.    , 0.    , ..., 0.6433, 1.    , 0.    ],
       [0.    , 0.1367, 0.4506, ..., 0.    , 0.    , 1.    ]])

# Y9YA 유사도 계산은 했지만 해당 인덱스가 어떤 기업인지 모린다.

In [29]:
# company와 index를 매핑할 딕셔너리 만들깅

company2idx = {}
for i, c in enumerate(df['company']): 
    company2idx[i] = c
    
# idx와 company를 매핑할 딕셔너리 만들깅

idx2company = {}
for i, c in company2idx.items(): idx2company[c] = i

In [30]:
company2idx[0]

'디휴브(DEHUV)'

In [33]:
idx2company

{'디휴브(DEHUV)': 0,
 '㈜레미유코스메틱': 1,
 '㈜순진': 17523,
 '효성에프엠에스㈜': 3,
 '㈜빗썸코리아': 3506,
 '미디어윌': 245,
 '만도브로제㈜': 6,
 '(재)서울관광재단': 7,
 '㈜나라물산': 440,
 '㈜블록체인기술연구소': 9,
 '㈜미디어윌': 29687,
 '㈜세종통상': 11,
 '지이씨엘코리아': 3822,
 '㈜나이콤': 13,
 '㈜우양': 14,
 '㈜피씨디렉트': 3447,
 '㈜더배려한': 16,
 '아임반': 17,
 '㈜더원 비앤에프': 18,
 '㈜시루정보': 19,
 '서준': 20,
 '㈜다원솔루텍': 21,
 '비테스코테크놀로지스코리아(유)': 22,
 '㈜이너스커뮤니티': 1688,
 '㈜브리지임팩트': 10840,
 '블루닉스㈜': 25,
 '㈜오버더리밋': 26,
 '㈜무창상사': 29200,
 '㈜주호데코': 28,
 '㈜체이스': 29,
 '㈜이피에스이앤이': 22838,
 '㈜스텝케어': 31,
 '㈜스타메드': 32,
 '㈜세상만사미디어': 33,
 '마켓디자이너스': 34,
 '㈜모두투어 네트워크': 35,
 '교원그룹': 1197,
 '도미노피자(청오디피케이)': 37,
 '씨비제이스타일컴퍼니㈜': 38,
 '㈜로원홀딩스': 39,
 '서경산업': 28736,
 '㈜에이유커머스': 23949,
 '㈜에이치엘더블유': 12742,
 '㈜단랩(DANLAB Inc.)': 13940,
 '㈜이마트에브리데이': 45,
 '콘티넨탈 오토모티브 일렉트로닉스 유한회사': 46,
 '주식회사 애드이피션시': 47,
 '오스템임플란트㈜': 12111,
 '동물나라수족관': 49,
 '큐브플랫폼㈜': 924,
 '게스홀딩스코리아 유한회사': 13320,
 '㈜농협정보시스템': 52,
 '세중에스비': 53,
 '에스케이임업㈜': 54,
 '오케이몰': 2131,
 '현대글로비스㈜': 56,
 '㈜딤커뮤니케이션': 57,
 'KB캐피탈㈜': 58,
 '㈜여우커뮤니케이션': 59,
 

# 아프리카TV 채용정보랑 비슷한 기업 찾아보깅

In [43]:
# 1. 아프리카티비 index 추출
idx = idx2company['㈜아프리카TV']
idx

1571

In [41]:
# 자기 자신을 제외한 기업들의 유사도 및 인덱스 추출하깅
sim_scores = [(i, c) for i, c in enumerate(sim_table2[idx]) if i != idx]
# 유사도 높은 순으로 정렬
sim_scores = sorted(sim_scores, key= lambda x: x[1], reverse=True)
sim_scores[0:10]

[(24566, 0.8218129902457738),
 (1826, 0.7777192509460735),
 (2170, 0.77663110387459),
 (2167, 0.750841582038223),
 (5006, 0.739681640437432),
 (12444, 0.7373559869099248),
 (9817, 0.720707917964622),
 (4607, 0.7202041348822963),
 (20499, 0.7182637857705145),
 (7306, 0.7172481825765354)]

In [42]:
# 인덱스를 기업명으로 바까주깅
sim_scores = [(company2idx[i], score) for i, score in sim_scores[0:10]]
sim_scores

[('미스터픽', 0.8218129902457738),
 ('바른경제티브이㈜', 0.7777192509460735),
 ('트리플하이엠', 0.77663110387459),
 ('㈜엠포스', 0.750841582038223),
 ('㈜수학에 심장을 달다', 0.739681640437432),
 ('아이엠에스모빌리티㈜', 0.7373559869099248),
 ('㈜슈퍼브에이아이', 0.720707917964622),
 ('㈜아토머스', 0.7202041348822963),
 ('이지스케이㈜', 0.7182637857705145),
 ('링크캠퍼스', 0.7172481825765354)]

# 우리은행 채용정보랑 비슷한 회사

In [46]:
idx2 = idx2company['㈜우리은행']
idx2
# 자기 자신을 제외한 기업들의 유사도 및 인덱스 추출하깅
sim_scores = [(i, c) for i, c in enumerate(sim_table2[idx2]) if i != idx2]
# 유사도 높은 순으로 정렬
sim_scores = sorted(sim_scores, key= lambda x: x[1], reverse=True)
sim_scores[0:10]
# 인덱스를 기업명으로 바까주깅
sim_scores = [(company2idx[i], score) for i, score in sim_scores[0:10]]
sim_scores

[('㈜두꺼비세상', 1.0000000000000002),
 ('㈜엔씨소프트', 1.0000000000000002),
 ('㈜유비온', 1.0000000000000002),
 ('카카오페이', 1.0000000000000002),
 ('이케이 주식회사', 1.0000000000000002),
 ('㈜티킷', 1.0000000000000002),
 ('마이스터정보기술㈜', 1.0000000000000002),
 ('애니메디솔루션㈜', 1.0000000000000002),
 ('스파이크', 1.0000000000000002),
 ('㈜누리미디어', 1.0000000000000002)]